### ISSUE TITLE
On 3.0.0 and PMS 1.27.x.x. Had to roll back PMS to 1.26.x.x but PlexDVrWaker no longer Works

### ISSUE THREAD

**Issue by nelcaps** [kmahon37/plex-dvr-waker#39]
I am getting this…

C;\PlexDVR>PlexDvrWaker.exe list --database=“C:\Users\plexuser\AppData\Local\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.db”
ERROR: System.InvalidCastException: Specified cast is not valid.
at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
at System.Data.SQLite.SQLiteDataReader.GetInt64(Int32 i)
at PlexDvrWaker.Plex.DataAdapter.LoadEpgInfo()
at PlexDvrWaker.Plex.DataAdapter.GetScheduledRecordings()
at PlexDvrWaker.Plex.DataAdapter.PrintScheduledRecordings()
at PlexDvrWaker.Program.RunList(ListOptions options)
at PlexDvrWaker.Program.RunVerb[T](T options, Func`2 verbFunc
[PlexDvrWaker.log](https://github.com/kmahon37/plex-dvr-waker/files/9060343/PlexDvrWaker.log)
[PlexDvrWaker.log](https://github.com/kmahon37/plex-dvr-waker/files/9060345/PlexDvrWaker.log)
)

**Comment by kmahon37** [comment]
You'll have to go back to PlexDvrWaker v2.1.2.  PMS v1.26.2.5797+ changed their database schema which I had to fix in v2.1.3+.
